### PR TITLE
BETA - Add blueprint and Update Readme

### PR DESCRIPTION
**Pull request by N1co93**
Hello,

I created a blueprint, so the creation of the Home Assistant Automation should be easier for the user. 
I only edited the "BETA", because I first like to know your opinion about it. If you like the idea, I can also edit the "production".

If we are going to use the blueprint inside the production, I also will create an easy button "IMPORT BLUEPRINT TO MY" image
Sadly this isn't possible for the "BETA", because the spaces inside the path.

### CODE REVIEW

**Comment by thiagobruch** [comment]
Hi @N1c093,

That is a great idea.
When you said "Sadly this isn't possible for the "BETA", because the spaces inside the path." are you talking about this name "BETA - alexa_shopping_list_scrapper" of the directory?
If so, I can change the directory to something like "BETA_alexa_shopping_list_scrapper". Would this work?
* sorry I'm new on github so I'm still learning how it works.

Thank you.

**Comment by thiagobruch** [comment]
Hi @N1c093 

Thank you for the help.
I was able to rename the directory and add the Blueprint link with the image.

thank you.

**Comment by N1co93** [comment]
Sorry, I was busy the last hours.
Great, that you manged it by yourself 👍

Do we want to add the blueprint also to the "production" the next days?

**Comment by thiagobruch** [comment]
Hi @N1c093 ,

I will try to add that to the "prod".
Do you know if there is a way to "copy" everything from the Beta Directory to the Prod Directory?
I started to better understand the branches, but I don't know how I would use a different branch and test it on Home Assistant.
Based on the above, you can tell that I'm not a developer at all LOL

**Comment by N1co93** [comment]
Sadly I don't know a better solution. I also don't have that much experiences with Github.

The big add-ons like "Frigate" also uses different folder and not branches. https://github.com/blakeblackshear/frigate-hass-addons

Maybe you can learn something from that project.

**Pull request merged**
